### ISSUE TITLE
Figure out client-server request timeline

### ISSUE THREAD

**Issue by mycrobe** [warelab/gramoogle#21]
gramoogle requires search results in a number of different forms:
* Summary statistics for filter summary
* List of genes for list view (may not be visible)
* Results faceted by genomic location bin.
  * Genes are in multiple bins for different resolution (e.g. 1Mb, 2Mb, 10Mb).
  * Only one of these would be used at a time.
* Results faceted to provide counts for the filter UI (interpro domain, go term etc)

Should these all be requested separately? By components when required? Bundled into one SOLR request with a large body?

**Comment by ajo2995** [comment]
I imagine there will be a mix of requests for data that fire under different circumstances.

1. Typeahead requests
2. list of genes for list view
3. Taxonomic and genomic location distributions
4. Other filters

1. Typeahead should be as lean as possible. If we don't care about suggestions being compatible with active filters, the suggest requestHandler in solr can do the job. Otherwise, we need to use the select requestHandler with a minimal response document and no facet counting. If we want to query across multiple cores, and keep the suggestions relevant to the current result set it gets more complicated and requires an intermediate service to integrate the responses from multiple cores. I'm leaning toward setting up an intermediate service anyway in case it becomes necessary to do complex things without complicating gramoogle.

2. The list of genes contains more information than the typeahead responses and is definitely subject to any filters that have been defined. The nrows query parameter can be set to something small in the request that provides the taxonomic and genomic location distributions. Subsequent requests triggered by scrolling can happen without facet counting.

3. The taxonomic and genomic location distributions differ from other filters in that they need to be requested with facet.limit=-1 (default is to limit to 100).

4. Other filters are not shown until the Filters tab is opened. Therefore, if it is not open, the solr request with those facet fields should happen separately from the request that provides the gene list and tax&gen distributions (2 & 3). The filter summary view shows each filter field with the exact number of terms in the result set or ">100". The term counts need to be calculated from the solr response for each facet.field because solr doesn't do it for you. The same solr response contains the necessary info to populate each filter. A filter may need to request useful info from an associated solr core such as domain name and description given a list of interpro ids. When a specific filter is being displayed, additional facet terms beyond the top 100 most popular w.r.t. the gene result set may be retrieved for just this facet with facet.offset=100.
